### ISSUE TITLE
collector.tsdb.could-not-connect

### ISSUE THREAD

**Issue by pawel2-grape** [cloudfoundry/collector#27]
I've met weird issue with collector and there are steps to reproduce:
<b>1) Cloud Foundry is working properly...</b>

<b>2) I've changed my CF manifest adding some properties and deploy changes.</b>
```vim
properties:
  collector:
    use_tsdb: true
    deployment_name: cf
    logging_level: debug
    opentsdb:
      address: 10.10.0.251
      port: 4567
```

<b>3) Everything is good and I have tcp on target machine on port 4567.</b>

<b>4) I've stopped AWS instances.</b>

<b>5) I've started AWS instances.</b>

<b>6) Re-deploy Cloud Foundry (because there are failing machines).</b>
```vim
bosh download manifest cf /tmp/cf_manifest && bosh deployment /tmp/cf_manifest && bosh -n deploy
```
But this throws an error:
```vim
Error 400007: `stats_z1/0' is not running after update
```

So... SSH to stats_z1 and 'monit summary':
```vim
The Monit daemon 5.2.4 uptime: 11m 

Process 'collector'                 Does not exist
Process 'metron_agent'              running
System 'system_1a7b4a29-97cd-4c1a-b9f7-db3d82ffabee' running
```
And logs from /var/vcap/sys/log/collector/collector.log
```vim
{"timestamp":1440668956.9306872,"message":"collector.tsdb.could-not-connect","log_level":"fatal","source":"collector","data":{},"thread_id":70274369442600,"fiber_id":70274370588860,"process_id":4201,"file":"/var/vcap/data/packages/collector/2644a3d4929a93b575dc61ebe28fd9b7a2bd1745.1-7e4f7b2f3b07c792473e110bfb05f6612807b688/lib/collector/tcp_connection.rb","lineno":25,"method":"unbind"}
```

After some debug I've discovered that @port and @ip variables are empty in 'tcp_connection.rb'... Why?

<b>7) To properly deploy I can set properties like that:</b>
```vim
properties:
  collector:
    use_tsdb: false
    deployment_name: cf
    logging_level: debug
    opentsdb:
      address: 10.10.0.251
      port: 4567
```
Or:
```vim
properties:
  collector:
    use_tsdb: true
    deployment_name: cf
    logging_level: debug
```
But of course then I don't have any data from collector.

Do you have any ideas why it's happens? Why @port and @ip are empty if I place suitable values in manifest?
I can add that I am using CF v214 on AWS us-east-1 region.

**Comment by pawel2-grape** [comment]
That error is caused by EventMachine which runs function 'unbind' from 'tcp_connection.rb' in time intervals after Collector object is created. In started function there are (like I write earlier) empty variables @port and @ip.
That's all what I can write about this issue.

Finally I was able to deploy CF with tsdb enabled by:
```vim
bosh stop stats_z1 --force
```
But this does not solve the problem, I am looking for someone's response with cause of this weird behavior...:)

**Comment by Jim-Campbell** [comment]
@pawel2-grape, we've looked at this as part of our scan of pending issues, and we believe you are better served by posting this issue to the cf-dev mailing list. It seems more a configuration issue than a problem with the collector.

**Comment by pawel2-grape** [comment]
Ok then, thanks for response.
